<?php
/*Arreglos de los datos para los selects del formulario*/
return [
    'estados' => [
        ['id' => 1, 'nombre' => 'Aguascalientes'],
        ['id' => 2, 'nombre' => 'Baja California'],
        ['id' => 3, 'nombre' => 'Baja California Sur'],
        ['id' => 4, 'nombre' => 'Campeche'],
        ['id' => 5, 'nombre' => 'Coahuila'],
        ['id' => 6, 'nombre' => 'Colima'],
        ['id' => 7, 'nombre' => 'Chiapas'],
        ['id' => 8, 'nombre' => 'Durango'],
        ['id' => 9, 'nombre' => 'Guanajuato'],
        ['id' => 10, 'nombre' => 'Guerrero'],
        ['id' => 11, 'nombre' => 'Hidalgo'],
        ['id' => 12, 'nombre' => 'Jalisco'],
        ['id' => 13, 'nombre' => 'México'],
        ['id' => 14, 'nombre' => 'Michoacán'],
        ['id' => 15, 'nombre' => 'Morelos'],
        ['id' => 16, 'nombre' => 'Nayarit'],
        ['id' => 17, 'nombre' => 'Nuevo León'],
        ['id' => 18, 'nombre' => 'Oaxaca'],
        ['id' => 19, 'nombre' => 'Puebla'],
        ['id' => 20, 'nombre' => 'Querétaro'],
        ['id' => 21, 'nombre' => 'Quintana Roo'],
        ['id' => 22, 'nombre' => 'San Luis Potosí'],
        ['id' => 23, 'nombre' => 'Sinaloa'],
        ['id' => 24, 'nombre' => 'Sonora'],
        ['id' => 25, 'nombre' => 'Tabasco'],
        ['id' => 26, 'nombre' => 'Tamaulipas'],
        ['id' => 27, 'nombre' => 'Tlaxcala'],
        ['id' => 28, 'nombre' => 'Veracruz'],
        ['id' => 29, 'nombre' => 'Yucatán'],
        ['id' => 30, 'nombre' => 'Zacatecas'],
        ['id' => 31, 'nombre' => 'Ciudad de México'],
    ],
    'grados' => [
        ['id' => 1, 'nombre' => 'Primaria'],
        ['id' => 2, 'nombre' => 'Secundaria'],
        ['id' => 3, 'nombre' => 'Bachillerato'],
        ['id' => 4, 'nombre' => 'Carrera técnica'],
        ['id' => 5, 'nombre' => 'Licenciatura/Ingeniería'],
        ['id' => 6, 'nombre' => 'Especialidad'],
        ['id' => 7, 'nombre' => 'Maestría'],
        ['id' => 8, 'nombre' => 'Doctorado'],
        ['id' => 9, 'nombre' => 'Sin estudios'],
    ],
    'sexo' => [
        ['id' => 1, 'nombre' => 'Masculino'],
        ['id' => 2, 'nombre' => 'Femenino'],
    ]
];
